// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ERC721} from "openzeppelin/token/ERC721/ERC721.sol";
import {Ownable} from "openzeppelin/access/Ownable.sol";
import {MerkleProof} from "openzeppelin/utils/cryptography/MerkleProof.sol";

/**
 * @notice ERC-7857 IntelligentData struct — matches 0G spec exactly.
 * @param dataDescription  Human-readable label for this data record.
 * @param dataHash         0G Storage root hash of the uploaded content (bytes32).
 */
struct IntelligentData {
  string dataDescription;
  bytes32 dataHash;
}

/**
 * @notice Journey metadata stored per token.
 * @param sessionId        UUID of the Rust orchestration session.
 * @param tripDescription  Human-readable trip summary (e.g. "Tokyo 5d $1200 USD").
 * @param createdAt        Block timestamp when the journey token was minted.
 * @param completedAt      Block timestamp when both collections were finalised (0 = incomplete).
 */
struct JourneyMeta {
  string sessionId;
  string tripDescription;
  uint256 createdAt;
  uint256 completedAt;
}

/**
 * @title  OpenWorldJourney
 * @notice ERC-7857 Intelligent NFT for OpenWorld autonomous travel agents.
 *
 * Each token = one completed journey execution.
 * After the Rust pipeline finishes, the agent uploads two payloads to 0G Storage
 * and calls mintAndRecord() to produce an immutable on-chain record.
 *
 * ── Two IntelligentData collections per token ────────────────────────────────
 *
 *   Collection 1 — JSON Context Memory
 *     Stores the full agent execution context: session policy, AI-generated
 *     itinerary, booking results, vault ledger, and activity logs — serialised
 *     to JSON and uploaded to 0G Storage.
 *     Each IntelligentData entry → one 0G Storage root hash (JSON blob).
 *
 *   Collection 2 — Report Root
 *     Stores the 0G Storage root hash of the final Markdown travel report
 *     generated by ArtifactAgent and uploaded to 0G Storage.
 *     Each IntelligentData entry → one 0G Storage root hash (Markdown file).
 *
 * ── ERC-7857 key functions ───────────────────────────────────────────────────
 *   intelligentDatasOf(tokenId)        → combined memory + report IntelligentData[]
 *   update(tokenId, IntelligentData[]) → routes to updateMemory (generic ERC-7857)
 *
 * ── OpenWorld-specific ───────────────────────────────────────────────────────
 *   mintJourney(to, agent, sessionId, tripDescription)
 *   updateMemory(tokenId, IntelligentData[])
 *   updateReport(tokenId, IntelligentData[])
 *   mintAndRecord(sessionId, trip, memHash, repHash) → convenience: mint + both updates
 *   verifyJourney(tokenId)             → hasMemory, hasReport, complete
 *   memoryOf(tokenId)                  → Collection 1
 *   reportOf(tokenId)                  → Collection 2
 *
 * Deployed on 0G Mainnet (chain ID 16661).
 */
contract OpenWorldJourney is ERC721, Ownable {
  uint256 private _nextTokenId;

  // ── Collection 1: JSON Context Memory ─────────────────────────────────────
  /// Current memory IntelligentData per token
  mapping(uint256 => IntelligentData[]) private _memoryDatas;
  /// Full snapshot history of memory updates per token
  mapping(uint256 => IntelligentData[][]) private _memoryHistory;

  // ── Collection 2: Report Root ──────────────────────────────────────────────
  /// Current report IntelligentData per token
  mapping(uint256 => IntelligentData[]) private _reportDatas;
  /// Full snapshot history of report updates per token
  mapping(uint256 => IntelligentData[][]) private _reportHistory;

  // ── Journey metadata ───────────────────────────────────────────────────────
  mapping(uint256 => JourneyMeta) public journeyMeta;

  /// Authorized agent wallet per token (Rust process that calls update functions)
  mapping(uint256 => address) public agentAddress;

  // ── Global Journey Merkle Tree ─────────────────────────────────────────────
  // Each completed journey adds a leaf:
  //   keccak256(tokenId || memoryHash || reportHash || block.timestamp)
  // journeyMerkleRoot grows monotonically — any journey can be inclusion-proved
  // using the leaf index and a standard Merkle proof.

  /// All accumulated journey completion leaves
  bytes32[] public journeyLeaves;

  /// Current Merkle root over all journeyLeaves
  bytes32 public journeyMerkleRoot;

  // ── Events ─────────────────────────────────────────────────────────────────

  /// @notice Emitted when a new journey token is minted
  event JourneyMinted(uint256 indexed tokenId, address indexed to, address indexed agent, string sessionId);

  /// @notice Emitted after updateMemory() — Collection 1 updated
  event MemoryUpdated(uint256 indexed tokenId, IntelligentData[] newDatas);

  /// @notice Emitted after updateReport() — Collection 2 updated
  event ReportUpdated(uint256 indexed tokenId, IntelligentData[] newDatas);

  /// @notice Emitted when both collections are finalised — journey is complete
  event JourneyCompleted(
    uint256 indexed tokenId,
    bytes32 indexed leaf,
    uint256 leafIndex,
    bytes32 newMerkleRoot
  );

  /// @notice One-stop event: owner address + markdown report root hash together.
  ///         Frontend queries this event filtered by owner to get all report hashes
  ///         and download reports directly from 0G Storage — no extra contract calls needed.
  event ReportPublished(
    address indexed owner,
    bytes32 indexed reportHash,
    uint256 indexed tokenId,
    string  sessionId
  );

  /// @notice ERC-7857 required event (generic intelligence update)
  event Updated(uint256 indexed tokenId, IntelligentData[] oldDatas, IntelligentData[] newDatas);

  // ── Constructor ───────────────────────────────────────────────────────────

  constructor() ERC721("OpenWorld Journey", "OWJ") {}

  // ── Minting ───────────────────────────────────────────────────────────────

  /**
   * @notice Mint a new journey token.
   *         Call this at session start; the agent updates collections later.
   * @param to              Owner of the journey token.
   * @param agent           Authorized agent wallet that will call update functions.
   * @param sessionId       Rust orchestration session UUID.
   * @param tripDescription Human-readable trip summary.
   */
  function mintJourney(
    address to,
    address agent,
    string calldata sessionId,
    string calldata tripDescription
  )
    external
    onlyOwner
    returns (uint256 tokenId)
  {
    require(to != address(0), "Zero address");
    require(bytes(sessionId).length > 0, "Empty sessionId");
    tokenId = _nextTokenId++;
    _safeMint(to, tokenId);
    agentAddress[tokenId] = agent;
    journeyMeta[tokenId] = JourneyMeta({
      sessionId: sessionId,
      tripDescription: tripDescription,
      createdAt: block.timestamp,
      completedAt: 0
    });
    emit JourneyMinted(tokenId, to, agent, sessionId);
  }

  /**
   * @notice Convenience: mint + record both collections in one transaction.
   *         Called by the Rust agent after uploading both payloads to 0G Storage.
   * @param owner            Wallet address that will own the journey NFT (from trip.md).
   * @param sessionId        Rust orchestration session UUID.
   * @param tripDescription  Human-readable trip summary.
   * @param memoryHash       0G Storage root hash of the agent JSON context blob.
   * @param reportHash       0G Storage root hash of the Markdown travel report.
   */
  function mintAndRecord(
    address owner,
    string calldata sessionId,
    string calldata tripDescription,
    bytes32 memoryHash,
    bytes32 reportHash
  )
    external
    onlyOwner
    returns (uint256 tokenId)
  {
    require(owner != address(0), "Zero owner address");
    require(bytes(sessionId).length > 0, "Empty sessionId");
    tokenId = _nextTokenId++;
    _safeMint(owner, tokenId);
    agentAddress[tokenId] = msg.sender;

    journeyMeta[tokenId] = JourneyMeta({
      sessionId: sessionId,
      tripDescription: tripDescription,
      createdAt: block.timestamp,
      completedAt: 0
    });

    // Set Collection 1 — JSON Context Memory
    string memory memDesc = string.concat("OpenWorld Memory | ", tripDescription);
    _memoryDatas[tokenId].push(IntelligentData({dataDescription: memDesc, dataHash: memoryHash}));

    // Set Collection 2 — Report Root
    string memory repDesc = string.concat("OpenWorld Report | ", tripDescription);
    _reportDatas[tokenId].push(IntelligentData({dataDescription: repDesc, dataHash: reportHash}));

    // Mark complete and record Merkle leaf
    _finalise(tokenId, memoryHash, reportHash);

    emit JourneyMinted(tokenId, msg.sender, msg.sender, sessionId);
    emit MemoryUpdated(tokenId, _memoryDatas[tokenId]);
    emit ReportUpdated(tokenId, _reportDatas[tokenId]);    emit ReportPublished(owner, reportHash, tokenId, sessionId);  }

  // ── Collection 1: JSON Context Memory ─────────────────────────────────────

  /**
   * @notice Update the JSON context memory for a journey.
   *         Uploads a new 0G Storage root hash for the agent's execution context.
   *         Can be called multiple times (e.g. after each agent re-run).
   * @param tokenId  Journey token ID.
   * @param newDatas New IntelligentData entries — dataHash = 0G Storage root of JSON blob.
   */
  function updateMemory(uint256 tokenId, IntelligentData[] calldata newDatas) external {
    _requireAuthorized(tokenId);
    require(newDatas.length > 0, "Empty data");

    IntelligentData[] memory old = _memoryDatas[tokenId];
    if (old.length > 0) _memoryHistory[tokenId].push(old);

    delete _memoryDatas[tokenId];
    for (uint256 i = 0; i < newDatas.length; i++) {
      _memoryDatas[tokenId].push(newDatas[i]);
    }

    emit MemoryUpdated(tokenId, newDatas);
    emit Updated(tokenId, old, newDatas); // ERC-7857

    _tryFinalise(tokenId);
  }

  // ── Collection 2: Report Root ──────────────────────────────────────────────

  /**
   * @notice Update the Markdown report root for a journey.
   *         Records the 0G Storage root hash of the generated travel report.
   * @param tokenId  Journey token ID.
   * @param newDatas New IntelligentData entries — dataHash = 0G Storage root of Markdown file.
   */
  function updateReport(uint256 tokenId, IntelligentData[] calldata newDatas) external {
    _requireAuthorized(tokenId);
    require(newDatas.length > 0, "Empty data");

    IntelligentData[] memory old = _reportDatas[tokenId];
    if (old.length > 0) _reportHistory[tokenId].push(old);

    delete _reportDatas[tokenId];
    for (uint256 i = 0; i < newDatas.length; i++) {
      _reportDatas[tokenId].push(newDatas[i]);
    }

    emit ReportUpdated(tokenId, newDatas);

    _tryFinalise(tokenId);
  }

  // ── ERC-7857 Required Interface ────────────────────────────────────────────

  /**
   * @notice ERC-7857: returns all IntelligentData for a token.
   *         Returns memory entries first, then report entries.
   */
  function intelligentDatasOf(uint256 tokenId) external view returns (IntelligentData[] memory result) {
    uint256 mLen = _memoryDatas[tokenId].length;
    uint256 rLen = _reportDatas[tokenId].length;
    result = new IntelligentData[](mLen + rLen);
    for (uint256 i = 0; i < mLen; i++) result[i] = _memoryDatas[tokenId][i];
    for (uint256 i = 0; i < rLen; i++) result[mLen + i] = _reportDatas[tokenId][i];
  }

  /**
   * @notice ERC-7857: generic update — routes to updateMemory.
   */
  function update(uint256 tokenId, IntelligentData[] calldata newDatas) external {
    _requireAuthorized(tokenId);
    require(newDatas.length > 0, "Empty data");

    IntelligentData[] memory old = _memoryDatas[tokenId];
    if (old.length > 0) _memoryHistory[tokenId].push(old);

    delete _memoryDatas[tokenId];
    for (uint256 i = 0; i < newDatas.length; i++) {
      _memoryDatas[tokenId].push(newDatas[i]);
    }

    emit Updated(tokenId, old, newDatas);
    emit MemoryUpdated(tokenId, newDatas);
    _tryFinalise(tokenId);
  }

  // ── View ──────────────────────────────────────────────────────────────────

  /// @notice Collection 1: current JSON context memory entries
  function memoryOf(uint256 tokenId) external view returns (IntelligentData[] memory) {
    return _memoryDatas[tokenId];
  }

  /// @notice Collection 2: current Markdown report entries
  function reportOf(uint256 tokenId) external view returns (IntelligentData[] memory) {
    return _reportDatas[tokenId];
  }

  /// @notice Full history of Collection 1 updates
  function memoryHistoryOf(uint256 tokenId) external view returns (IntelligentData[][] memory) {
    return _memoryHistory[tokenId];
  }

  /// @notice Full history of Collection 2 updates
  function reportHistoryOf(uint256 tokenId) external view returns (IntelligentData[][] memory) {
    return _reportHistory[tokenId];
  }

  /**
   * @notice Verify a journey's on-chain completeness.
   * @return hasMemory  True if Collection 1 (JSON) has been recorded.
   * @return hasReport  True if Collection 2 (Report) has been recorded.
   * @return complete   True if both collections are recorded and journey is finalised.
   */
  function verifyJourney(uint256 tokenId)
    external
    view
    returns (bool hasMemory, bool hasReport, bool complete)
  {
    hasMemory = _memoryDatas[tokenId].length > 0;
    hasReport = _reportDatas[tokenId].length > 0;
    complete = journeyMeta[tokenId].completedAt != 0;
  }

  /**
   * @notice Prove a journey leaf is in the Merkle tree.
   * @param leaf   The leaf bytes32 to verify.
   * @param proof  Standard Merkle inclusion proof.
   */
  function verifyLeaf(bytes32 leaf, bytes32[] calldata proof) external view returns (bool) {
    return MerkleProof.verify(proof, journeyMerkleRoot, leaf);
  }

  /// @notice Total number of journey tokens minted
  function totalSupply() external view returns (uint256) {
    return _nextTokenId;
  }

  /// @notice Total number of completed (fully finalised) journeys recorded
  function totalCompletedJourneys() external view returns (uint256) {
    return journeyLeaves.length;
  }

  // ── Internal ──────────────────────────────────────────────────────────────

  function _requireAuthorized(uint256 tokenId) internal view {
    require(_exists(tokenId), "Token does not exist");
    require(msg.sender == agentAddress[tokenId] || msg.sender == owner(), "Not authorized");
  }

  /// Finalise the journey if both collections are set and not yet finalised
  function _tryFinalise(uint256 tokenId) internal {
    if (
      _memoryDatas[tokenId].length > 0
        && _reportDatas[tokenId].length > 0
        && journeyMeta[tokenId].completedAt == 0
    ) {
      _finalise(tokenId, _memoryDatas[tokenId][0].dataHash, _reportDatas[tokenId][0].dataHash);
    }
  }

  function _finalise(uint256 tokenId, bytes32 memHash, bytes32 repHash) internal {
    journeyMeta[tokenId].completedAt = block.timestamp;

    // Leaf = keccak256(tokenId || memoryHash || reportHash || timestamp) — unique per journey
    bytes32 leaf = keccak256(abi.encodePacked(tokenId, memHash, repHash, block.timestamp));
    uint256 leafIndex = journeyLeaves.length;
    journeyLeaves.push(leaf);
    journeyMerkleRoot = _computeMerkleRoot();

    emit JourneyCompleted(tokenId, leaf, leafIndex, journeyMerkleRoot);
  }

  /// @dev Standard binary Merkle tree over journeyLeaves
  function _computeMerkleRoot() internal view returns (bytes32) {
    uint256 len = journeyLeaves.length;
    if (len == 0) return bytes32(0);

    bytes32[] memory nodes = new bytes32[](len);
    for (uint256 i = 0; i < len; i++) {
      nodes[i] = journeyLeaves[i];
    }

    while (nodes.length > 1) {
      uint256 newLen = (nodes.length + 1) / 2;
      bytes32[] memory next = new bytes32[](newLen);
      for (uint256 i = 0; i < newLen; i++) {
        uint256 left = i * 2;
        uint256 right = left + 1 < nodes.length ? left + 1 : left;
        next[i] = keccak256(abi.encodePacked(nodes[left], nodes[right]));
      }
      nodes = next;
    }

    return nodes[0];
  }
}
